### ISSUE TITLE
Plans to make the api realtime?

### ISSUE THREAD

**Issue by joeblackwaslike** [PredixDev/predix-volcano-app#3]
Any chance the api will include realtime data in the future or is all the data for this already collected and static?

**Comment by j12y** [comment]
There was a plan to stream data through a message broker but ultimately the sensor nodes couldn't survive the corrosive elements of the volcano.  As such this is just a static data set and reference implementation.  One goal and outcome for the project was to gain insights into which sensors and locations within the volcano were of greatest value.  I could imagine the same API and services being utilized with a different volcano, node locations, and sensor set -- but I'm not aware of any timelines around a follow-up project at this time.
