### ISSUE TITLE
README.md - Predix Logo not displayed

### ISSUE THREAD

**Issue by ChaiBapchya** [PredixDev/predix-volcano-app#4]
In the readme.md file, at the bottom, there is an image which isn't being displayed.
URL is broken (not working). As a result, it is not being shown.
Can be easily fixable by linking to the correct link.

**Comment by j12y** [comment]
Hi, thanks for reporting.  That's an analytics beacon that is intended to show a blank pixel and be used for tracking.
https://github.com/igrigorik/ga-beacon

It looks like the account may be over quota though @turnerth.

```
$ curl -I https://ga-beacon.appspot.com/UA-82773213-1/predix-volcano-app/readme?pixel
HTTP/1.1 503 Service Unavailable
X-Cloud-Trace-Context: e19ed025f0a752246d1c3f6ab321472f
Date: Mon, 18 Sep 2017 06:09:13 GMT
Content-Type: text/html
Server: Google Frontend
Content-Length: 970
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,35"
```

**Comment by turnerth** [comment]
I don't see a limit error today.
