### ISSUE TITLE
Unable to make API calls using Postman

### ISSUE THREAD

**Issue by ChaiBapchya** [PredixDev/predix-volcano-app#5]
According to the API page - https://volcano-app.run.aws-usw02-pr.ice.predix.io/docs/html/api/index.html

I wanted to test the APIs.

Using Postman,
How should I make the GET/POST requests?

For example, this is a given sample
```
GET /api/1.0/volcano/35dc3e90-8679-11e6-bda3-ef77801087ee HTTP/1.1
Host: predix-volcano.run.aws-usw02-pr.ice.predix.io
Accept: application/json
```
If i enter the above, URL seems to be incomplete.
Sorry for a rookie question.

**Comment by j12y** [comment]
Here's an example with `curl`:

```
$ curl https://volcano-app.run.aws-usw02-pr.ice.predix.io/api/1.0/volcanoes
[
  {
    "description": "This is the world's biggest, baddest, most evil volcano.",
    "location": "{11.985318299999999,-86.178342900000004}",
    "name": "Masaya",
    "status": "OFFLINE",
    "uri": "/volcano/35dc3e90-8679-11e6-bda3-ef77801087ee"
  }
]
```

Works the same in Postman by pasting the same URL, just be sure you include **https**.

The API at this url does not support writes (ie. POST or PUT) and is read-only.  If you want to change the volcano data, you will need to create your own running instance as described in [Getting Started](https://volcano-app.run.aws-usw02-pr.ice.predix.io/docs/html/getting-started/index.html) and then look for some of the tutorials on predix.io for Predix Asset and Time Series.

Hope that helps.

**Comment by ChaiBapchya** [comment]
However this URL = "https://volcano-app.run.aws-usw02-pr.ice.predix.io/api/1.0/volcanoes" is not given on the page.
Later I realized /api meant "https://volcano-app.run.aws-usw02-pr.ice.predix.io/" + /api

Anyway, thanks!

**Comment by j12y** [comment]
Glad you pieced it together.  The pattern as you determined is:

> $hostname + $relative_url

where $relative_url is `/api/$version/route`.  Anybody that deploys the app will have their own hostname, so http://localhost:8080 and https://predix-volcano and https://volcano-app are all capable of returning similar results for a GET on `/api/1.0/volcanoes`.

https://predix-volcano.run.aws-usw02-pr.ice.predix.io/docs/html/api/index.html#get--api-1.0-volcanoes

I'll see if I can make that clearer or provide more examples in the documentation.  It is based on what you would see from a `curl`:

```
$ curl -v https://volcano-app.run.aws-usw02-pr.ice.predix.io/api/1.0/volcanoes
*   Trying 52.42.56.74...
* Connected to volcano-app.run.aws-usw02-pr.ice.predix.io (52.42.56.74) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.run.aws-usw02-pr.ice.predix.io
* Server certificate: Trusted Secure Certificate Authority 5
* Server certificate: USERTrust RSA Certification Authority
> GET /api/1.0/volcanoes HTTP/1.1
> Host: volcano-app.run.aws-usw02-pr.ice.predix.io
> User-Agent: curl/7.43.0
> Accept: */*
```
